# Generated by Django 5.0 on 2023-12-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='mostra',
            new_name='mostrar',
        ),
    ]
