# Generated by Django 5.0 on 2023-12-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_contato_fot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='fot',
            new_name='foto',
        ),
    ]
